# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_market?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true&&useSSL=false
    username: root
    password: 020313wy...
  redis:
    #    database: 0
    host: 175.24.201.104
    port: 6379
    timeout: 30000
    password: ucpAXNge?)_4>PdF]_7i
    #    client-type: lettuce
    #    lettuce:
    #      pool:
    #        max-active: 10
    #        min-idle: 0
    #        max-idle: 1o
    #        max-wait: -2
# MyBatis mapper.xml路径配置
mybatis:
  # 指定 mapper.xml 的其它module位置
  mapper-locations: classpath*:mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: com.xdu.wjw.supermarketmodel.model.dao
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true